---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - 'AUTHOR_TESTING=0 cpanm Code::TidyAll::Plugin::SortLines::Naturally Code::TidyAll::Plugin::UniqueLines Perl::Tidy'
cache:
  directories:
    - '~/perl5'
language: perl
matrix: {}
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - olaf@wundersolutions.com
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
script:
  - 'prove -lrv t'
sudo: 'false'
